- name: install webservers, exporters and filebeat
  hosts: webservers
  become: yes
  tags: webservers
  roles:
  - webserver
  - node-exporter
  - filebeat

- name: install prometheus
  hosts: prometheus
  become: yes
  tags: prometheus
  roles:
  - prometheus

- name: install grafana
  hosts: grafana
  become: yes
  tags: grafana
  roles:
  - grafana

- name: install elasticsearch and logstash
  hosts: elastic
  become: yes
  tags: elastic
  roles:
  - elastic
  - logstash

- name: install kibana
  hosts: kibana
  become: yes
  tags: kibana
  roles:
  - kibana
